### 📘 Project Assignment: Analyzing Student Performance Using NumPy
#### 🎯 Objective:
##### Use NumPy to analyze and manipulate data for 10 students' performance in three subjects (Math, Science, English). You'll perform array creation, reshaping, indexing, slicing, statistical operations, broadcasting, boolean filtering, and more.

#### Step-by-Step NumPy Code and Explanation:


In [1]:
import numpy as np

# 1. Create the data array (10 students × 3 subjects)
data = np.array([
    [85, 78, 92],
    [76, 85, 88],
    [90, 91, 85],
    [65, 72, 78],
    [88, 89, 94],
    [70, 68, 72],
    [95, 94, 90],
    [60, 64, 67],
    [82, 80, 85],
    [77, 75, 70]
])

In [2]:
print(data)

[[85 78 92]
 [76 85 88]
 [90 91 85]
 [65 72 78]
 [88 89 94]
 [70 68 72]
 [95 94 90]
 [60 64 67]
 [82 80 85]
 [77 75 70]]


In [3]:
# Array Properties
print("Shape:", data.shape)       # (10, 3)
print("Size:", data.size)         # 30 (10x3)
print("Datatype:", data.dtype)    # int32 (usually)

Shape: (10, 3)
Size: 30
Datatype: int64


In [4]:
# Accessing and Slicing Data
print("Marks of Student 1:", data[0])           # First student's marks
print("All Math marks:", data[:, 0])            # First column
print("English marks of last 3 students:", data[-3:, 2])  # English column, last 3 rows

Marks of Student 1: [85 78 92]
All Math marks: [85 76 90 65 88 70 95 60 82 77]
English marks of last 3 students: [67 85 70]


In [5]:
# Modify an Element (Indexing)
data[0, 1] = 80  # Change Student 1's Science marks to 80

In [6]:
print(data)

[[85 80 92]
 [76 85 88]
 [90 91 85]
 [65 72 78]
 [88 89 94]
 [70 68 72]
 [95 94 90]
 [60 64 67]
 [82 80 85]
 [77 75 70]]


In [7]:
# Statistical Analysis
print("Mean marks per subject:", np.mean(data, axis=0))
print("Median:", np.median(data, axis=0))
print("Standard deviation:", np.std(data, axis=0))
print("Max per subject:", np.max(data, axis=0))
print("Min per subject:", np.min(data, axis=0))

Mean marks per subject: [78.8 79.8 82.1]
Median: [79.5 80.  85. ]
Standard deviation: [10.74057727  9.54777461  9.20271699]
Max per subject: [95 94 94]
Min per subject: [60 64 67]


In [8]:
# Total and Average per Student
total_per_student = np.sum(data, axis=1)
avg_per_student = np.mean(data, axis=1)

In [10]:
print(total_per_student)
print(avg_per_student)

[257 249 266 215 271 210 279 191 247 222]
[85.66666667 83.         88.66666667 71.66666667 90.33333333 70.
 93.         63.66666667 82.33333333 74.        ]


In [11]:
# Boolean Indexing
# Students with average > 85
high_achievers = data[avg_per_student > 85]
print("High Achievers:\n", high_achievers)

High Achievers:
 [[85 80 92]
 [90 91 85]
 [88 89 94]
 [95 94 90]]


In [12]:
# Broadcasting: Add Bonus Marks
bonus = np.array([2, 1, 0])  # Bonus for Math, Science, English
data_bonus = data + bonus
print(data_bonus)

[[87 81 92]
 [78 86 88]
 [92 92 85]
 [67 73 78]
 [90 90 94]
 [72 69 72]
 [97 95 90]
 [62 65 67]
 [84 81 85]
 [79 76 70]]


In [13]:
# Reshape and Flatten
flattened = data.flatten()        # 1D array
reshaped = flattened.reshape(5, 6)  # Reshape into 5x6
print(flattened)
print(reshaped)

[85 80 92 76 85 88 90 91 85 65 72 78 88 89 94 70 68 72 95 94 90 60 64 67
 82 80 85 77 75 70]
[[85 80 92 76 85 88]
 [90 91 85 65 72 78]
 [88 89 94 70 68 72]
 [95 94 90 60 64 67]
 [82 80 85 77 75 70]]


In [14]:
# Sorting
sorted_data = np.sort(data, axis=1)  # Sort each student’s marks
print(sorted)

<built-in function sorted>


In [15]:
# Unique and Count
print("Unique marks:", np.unique(data))

Unique marks: [60 64 65 67 68 70 72 75 76 77 78 80 82 85 88 89 90 91 92 94 95]


In [16]:
# Stacking Arrays
# Adding a new column: Total marks
data_with_total = np.hstack((data, total_per_student.reshape(-1, 1)))
print(data_with_total)

[[ 85  80  92 257]
 [ 76  85  88 249]
 [ 90  91  85 266]
 [ 65  72  78 215]
 [ 88  89  94 271]
 [ 70  68  72 210]
 [ 95  94  90 279]
 [ 60  64  67 191]
 [ 82  80  85 247]
 [ 77  75  70 222]]


### Assignment Tasks (For Practice):
- Identify the top 3 students based on total marks.

- Calculate the subject in which students scored the lowest average.

- Create a curve adjustment (e.g., add 5 marks to all English scores).

- Find students who failed in any subject (assume < 70 is fail).

- Visualize the Math scores using matplotlib (optional extra).